(* Generated by Frama-C WP *)

Goal typed_cast_caveat_nan_test2_ensures_7.
Hint default,nan_test2,property.
Proof.
(* --------------------------------------
  
From 'typed_caveat_nan_test2_ensures_5': 
(* --------------------------------------
  
From 'typed_nan_test2_ensures': 
  intros.
  unfold x.
  unfold F2___i.
(* auto with zarith. *)
*)
*)
(* --------------------------------------
  
From 'typed_nan_test2_ensures': 
  intros.
  unfold x.
  unfold F2___i.
(* auto with zarith. *)
*)
Qed.

Goal typed_caveat_nan_test2_ensures_5.
Hint default,nan_test2,property.
Proof.
(* --------------------------------------
  
From 'typed_nan_test2_ensures': 
  intros.
  unfold x.
  unfold F2___i.
(* auto with zarith. *)
*)
Qed.

Goal typed_fabs_ensures_3.
Hint default,fabs,property.
Proof.
  intros.
(* auto with zarith. *)
Qed.

Goal typed_nan_test2_ensures.
Hint default,nan_test2,property.
Proof.
  intros.
  unfold x.
  unfold F2___i.
(* auto with zarith. *)
Qed.

Goal typed_nat_real_nan_test2_ensures_10.
Hint default,nan_test2,property.
Proof.
(* --------------------------------------
  
From 'typed_caveat_nan_test2_ensures_5': 
(* --------------------------------------
  
From 'typed_nan_test2_ensures': 
  intros.
  unfold x.
  unfold F2___i.
(* auto with zarith. *)
*)
*)
(* --------------------------------------
  
From 'typed_nan_test2_ensures': 
  intros.
  unfold x.
  unfold F2___i.
(* auto with zarith. *)
*)
(* --------------------------------------
  
From 'typed_cast_caveat_nan_test2_ensures_7': 
(* --------------------------------------
  
From 'typed_caveat_nan_test2_ensures_5': 
(* --------------------------------------
  
From 'typed_nan_test2_ensures': 
  intros.
  unfold x.
  unfold F2___i.
(* auto with zarith. *)
*)
*)
(* --------------------------------------
  
From 'typed_nan_test2_ensures': 
  intros.
  unfold x.
  unfold F2___i.
(* auto with zarith. *)
*)
*)
Qed.


