(* Generated by Frama-C WP *)

Goal typed_strcat_ensures_s_copied.
Hint default,property,s_copied,strcat.
Proof.
  Require Import Lia.
  intros.
  unfold P_string_equal, P_array_equal_2_, P_array_equal_1_.
  split.
(* auto with zarith. *)
Qed.


