(* Generated by Frama-C WP *)

Goal typed_lemma_always_based.
Hint always_based,property.
Proof.
(* auto with zarith. *)
Qed.

Goal typed_lemma_always_based_2.
Hint always_based_2,property.
Proof.
(* auto with zarith. *)
Qed.


