(* Generated by Frama-C WP *)

Goal typed_strlen_ensures.
Hint default,property,strlen.
Proof.
  intros.

  rewrite id_uint32.
  +
    unfold x_2.
    rewrite A_StrLen.Q_pos_or_nul with (i := (x_1 - x)%Z).
    all: unfold x_2.
    all: auto with zarith.

    unfold P_based_2_, P_based_1_, P_based_ptr_1_, P_based_value_1_ in H8.
    destruct H8 as [h_based h_value].
    unfold Compound.shift_sint8, shift in h_value.

    assert (a1 = shift a2 (x1 - x))%Z.  {
      unfold shift, a2.
      simpl in H7.




      unfold Map.set in H7.
      unfold why_decidable_eq in H7.
      unfold addr_WhyType in H7.
      simpl in H7.
    }
    rewrite <- H9.
    auto.

    intros.

    apply Q_before_strlen.
    all: auto with zarith.
    
  + 
    unfold is_uint32. 
    split.
    auto with zarith.
    assert (x2 <= x3)%Z.
(* auto with zarith. *)
Qed.

Goal typed_strlen_loop_invariant_based_3_preserved.
Hint based,preserved,strlen.
Proof.
  intros.
  unfold P_based.
(* --------------------------------------
  
From 'typed_strlen_loop_invariant_under_len_4_preserved': 
(* auto with zarith. *)
*)
Qed.

Goal typed_strlen_loop_invariant_based_4_preserved.
Hint based,preserved,strlen.
Proof.
  Require Import Lia.
  intros.
  unfold P_based in H7.
  unfold P_based.
  destruct H7.
  unfold shift_sint8, shift in H7.
Qed.

Goal typed_strlen_loop_invariant_ptr_established.
Hint established,ptr,strlen.
Proof.
  unfold P_consistent_ptr.
  auto.
Qed.

Goal typed_strlen_loop_invariant_under_len_4_preserved.
Hint preserved,strlen,under_len.
Proof.
(* auto with zarith. *)
Qed.


