(* Generated by Frama-C WP *)

Goal typed_strncat_loop_invariant_limits_n_preserved.
Hint limits_n,preserved,strncat.
Proof.
  auto with zarith.
Qed.

Goal typed_strncat_loop_invariant_limits_pos_preserved.
Hint limits_pos,preserved,strncat.
Proof.
  auto with zarith.
Qed.


